sudo: false
language: python
python:
    - 2.7
    - 3.2
    - 3.3
    - 3.4
    - "pypy"

env:
    - DJANGO_PACKAGE="Django>=1.7,<1.8"
    - DJANGO_PACKAGE="Django>=1.8,<1.9"

matrix:
    fast_finish: true

install:
    - python setup.py install
    - pip install "${DJANGO_PACKAGE:-Django}" 'coverage<4'
    - pip install -r requirements.txt

before_script:
    - cd demo_zinnia_tinymce

script:
    - coverage run manage.py test

after_success:
    - ./bin/coveralls

# notifications:
#     irc:
#         - "irc.freenode.org#django-blog-zinnia"
