sudo: false
language: python
python:
    - 2.7
    - 3.2
    - 3.3
    - 3.4
    - "pypy"
matrix:
    fast_finish: true
install:
    - pip install -U setuptools
    - python bootstrap.py
    - ./bin/buildout
before_script:
    - ./bin/flake8 zinnia_tinymce
script:
    - ./bin/demo test zinnia_tinymce
